name: 🚀 Release packages

on:
    release:
        types: [ released ]

env:
    RELEASE_VERSION: ${{ github.event.release.tag_name }}

permissions:
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        name: 🚀 Publish to Registry
        steps:
            -   name: 👀 Checkout
                uses: actions/checkout@v4

            -   name: 🍞 Setup Bun
                uses: oven-sh/setup-bun@v2

            -   name: ✏️ Tag v${{ env.RELEASE_VERSION }}
                run: |
                    bun pm version --cwd packages/tools ${{ env.RELEASE_VERSION }} --no-git-tag-version
                    bun pm version --cwd packages/utils ${{ env.RELEASE_VERSION }} --no-git-tag-version
                    bun pm version --cwd packages/vite-preset ${{ env.RELEASE_VERSION }} --no-git-tag-version
                    bun pm version --cwd packages/http-client ${{ env.RELEASE_VERSION }} --no-git-tag-version

            -   name: 📦️ Install dependencies
                run: bun install --frozen-lockfile

            -   name: 🔨 Build
                run: |
                    bun --cwd packages/tools build
                    bun --cwd packages/utils build
                    bun --cwd packages/vite-preset build
                    bun --cwd packages/http-client build

            -   name: 🚀 Publish v${{ env.RELEASE_VERSION }}
                run: |
                    bun publish --cwd packages/tools --access public
                    bun publish --cwd packages/utils --access public
                    bun publish --cwd packages/vite-preset --access public
                    bun publish --cwd packages/http-client --access public
                env:
                    NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
